server:
  port: 8090
logging:
  level:
    '[org.springframework]': info
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mytracker
  data:
    rest:
      base-path: /app/v2
mydata:
  input: DevProfile