server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 2
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krishnamurthypradeep/config-repo.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
